//
// Generated file, do not edit! Created by nedtool 4.6 from messages/ApplPkt.msg.
//

#ifndef _APPLPKT_M_H_
#define _APPLPKT_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
    #include "SimpleAddress.h"
// }}

/**
 * Class generated from <tt>messages/ApplPkt.msg:35</tt> by nedtool.
 * <pre>
 * // Basic application packet definition
 * //
 * // subclass if you want to create your own application layer packet
 * // class
 * //
 * // @author Daniel Willkomm
 * packet ApplPkt
 * {
 *     LAddress::L3Type destAddr = LAddress::L3BROADCAST; // destination address
 *     LAddress::L3Type srcAddr = LAddress::L3BROADCAST; // source address
 * }
 * </pre>
 */
class ApplPkt : public ::cPacket
{
  protected:
    LAddress::L3Type destAddr_var;
    LAddress::L3Type srcAddr_var;

  private:
    void copy(const ApplPkt& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ApplPkt&);

  public:
    ApplPkt(const char *name=NULL, int kind=0);
    ApplPkt(const ApplPkt& other);
    virtual ~ApplPkt();
    ApplPkt& operator=(const ApplPkt& other);
    virtual ApplPkt *dup() const {return new ApplPkt(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual LAddress::L3Type& getDestAddr();
    virtual const LAddress::L3Type& getDestAddr() const {return const_cast<ApplPkt*>(this)->getDestAddr();}
    virtual void setDestAddr(const LAddress::L3Type& destAddr);
    virtual LAddress::L3Type& getSrcAddr();
    virtual const LAddress::L3Type& getSrcAddr() const {return const_cast<ApplPkt*>(this)->getSrcAddr();}
    virtual void setSrcAddr(const LAddress::L3Type& srcAddr);
};

inline void doPacking(cCommBuffer *b, ApplPkt& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, ApplPkt& obj) {obj.parsimUnpack(b);}


#endif // ifndef _APPLPKT_M_H_

