//
// Generated file, do not edit! Created by nedtool 4.6 from messages/NetwPkt.msg.
//

#ifndef _NETWPKT_M_H_
#define _NETWPKT_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
    #include "SimpleAddress.h"
// }}

/**
 * Class generated from <tt>messages/NetwPkt.msg:39</tt> by nedtool.
 * <pre>
 * // A basic network layer packet definition
 * //
 * // subclass if you want to create your own network layer packet class
 * //
 * // The basic network packet contains a destination and source network address.
 * // Additionally a time to live (ttl) field can be defined in order to limit the
 * // maximum number of hops the messge will travel. The sequence number is guranteed
 * // to be unique for all packets generated by one host
 * //
 * // @author Daniel Willkomm
 * packet NetwPkt
 * {
 *     LAddress::L3Type destAddr;   // destination address
 *     LAddress::L3Type srcAddr;    // source address
 *     int ttl = 1; // time to live field (IP)
 *     unsigned long seqNum = 0; // sequence number
 * }
 * </pre>
 */
class NetwPkt : public ::cPacket
{
  protected:
    LAddress::L3Type destAddr_var;
    LAddress::L3Type srcAddr_var;
    int ttl_var;
    unsigned long seqNum_var;

  private:
    void copy(const NetwPkt& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const NetwPkt&);

  public:
    NetwPkt(const char *name=NULL, int kind=0);
    NetwPkt(const NetwPkt& other);
    virtual ~NetwPkt();
    NetwPkt& operator=(const NetwPkt& other);
    virtual NetwPkt *dup() const {return new NetwPkt(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual LAddress::L3Type& getDestAddr();
    virtual const LAddress::L3Type& getDestAddr() const {return const_cast<NetwPkt*>(this)->getDestAddr();}
    virtual void setDestAddr(const LAddress::L3Type& destAddr);
    virtual LAddress::L3Type& getSrcAddr();
    virtual const LAddress::L3Type& getSrcAddr() const {return const_cast<NetwPkt*>(this)->getSrcAddr();}
    virtual void setSrcAddr(const LAddress::L3Type& srcAddr);
    virtual int getTtl() const;
    virtual void setTtl(int ttl);
    virtual unsigned long getSeqNum() const;
    virtual void setSeqNum(unsigned long seqNum);
};

inline void doPacking(cCommBuffer *b, NetwPkt& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, NetwPkt& obj) {obj.parsimUnpack(b);}


#endif // ifndef _NETWPKT_M_H_

